import { TypeBug } from "@/api/bug/types";

export const bugs: TypeBug[] = [
  {
    id: "BUG-001",
    title: "Payment Gateway Error",
    cretedAt: "2024-01-15",
    projectId: "",
    status: "Process",
    severity: 100,
    waktu_perbaikan: 40,
    risiko_perbaikan: 40,
    prioritas_stakeholder: 100,
    usia_bug: 60,
    ketersediaan_sdm: 80,
    skor: 90,
  },
  {
    id: "BUG-002",
    title: "User Authentication Timeout",
    cretedAt: "2024-01-18",
    projectId: "",
    status: "Fixed",
    severity: 80,
    waktu_perbaikan: 60,
    risiko_perbaikan: 60,
    prioritas_stakeholder: 80,
    usia_bug: 40,
    ketersediaan_sdm: 60,
    skor: 90,
  },
  {
    id: "BUG-003",
    title: "Data Export Formatting",
    cretedAt: "2024-01-20",
    projectId: "",
    status: "Process",
    severity: 40,
    waktu_perbaikan: 80,
    risiko_perbaikan: 100,
    prioritas_stakeholder: 40,
    usia_bug: 20,
    ketersediaan_sdm: 100,
    skor: 52,
  },
  {
    id: "BUG-004",
    title: "Mobile Layout Breaking",
    cretedAt: "2024-01-22",
    projectId: "",
    status: "Process",
    severity: 60,
    waktu_perbaikan: 40,
    risiko_perbaikan: 80,
    prioritas_stakeholder: 60,
    usia_bug: 40,
    ketersediaan_sdm: 80,
    skor: 98,
  },
  {
    id: "BUG-005",
    title: "Database Connection Timeout",
    cretedAt: "2024-01-23",
    projectId: "",
    status: "Fixed",
    severity: 100,
    waktu_perbaikan: 20,
    risiko_perbaikan: 20,
    prioritas_stakeholder: 100,
    usia_bug: 20,
    ketersediaan_sdm: 100,
    skor: 63,
  },
  {
    id: "BUG-006",
    title: "Report Generation Failure",
    cretedAt: "2024-01-25",
    projectId: "",
    status: "Process",
    severity: 80,
    waktu_perbaikan: 60,
    risiko_perbaikan: 80,
    prioritas_stakeholder: 80,
    usia_bug: 40,
    ketersediaan_sdm: 60,
    skor: 70,
  },
  {
    id: "BUG-007",
    title: "Email Notification Delay",
    cretedAt: "2024-01-27",
    projectId: "",
    status: "Fixed",
    severity: 60,
    waktu_perbaikan: 80,
    risiko_perbaikan: 80,
    prioritas_stakeholder: 60,
    usia_bug: 40,
    ketersediaan_sdm: 80,
    skor: 67,
  },
  {
    id: "BUG-008",
    title: "Search Function Error",
    cretedAt: "2024-01-28",
    projectId: "",
    status: "Process",
    severity: 80,
    waktu_perbaikan: 40,
    risiko_perbaikan: 60,
    prioritas_stakeholder: 80,
    usia_bug: 20,
    ketersediaan_sdm: 60,
    skor: 20,
  },
  {
    id: "BUG-009",
    title: "Image Upload Error",
    cretedAt: "2024-01-30",
    projectId: "",
    status: "Process",
    severity: 40,
    waktu_perbaikan: 60,
    risiko_perbaikan: 100,
    prioritas_stakeholder: 40,
    usia_bug: 20,
    ketersediaan_sdm: 100,
    skor: 45,
  },
  {
    id: "BUG-010",
    title: "API Rate Limiting Issue",
    cretedAt: "2024-02-01",
    projectId: "",
    status: "Fixed",
    severity: 100,
    waktu_perbaikan: 20,
    risiko_perbaikan: 40,
    prioritas_stakeholder: 100,
    usia_bug: 20,
    ketersediaan_sdm: 80,
    skor: 80,
  },
];
